#!/bin/sh

if [ $# -lt 1 ]; then
	echo "Usage : $0 [{inc|dec|mute}] [play file]"
	exit 1
fi

if pgrep pulseaudio > /dev/null 2>&1 ; then
	# pulse audio volume control
	case "$1" in
	inc)	pactl set-sink-volume 0 -- '-5%' ;;
	dec)	pactl set-sink-volume 0 -- '+5%' ;;
	mute)	pactl set-sink-volume 0 0 ;;
	play)	paplay "$2" & ;;
	esac
elif pgrep sndiod >/dev/null 2>&1 ; then
	# sndio audio volume control
	case "$1" in
	inc)	aucatctl master=$(($(aucatctl | grep master | cut -f2 -d=)-6)) ;;
	dec)	aucatctl master=$(($(aucatctl | grep master | cut -f2 -d=)+6)) ;;
	mute)	aucatctl master=0 ;;
	play)	play -q "$2" & ;;
	esac
elif pgrep alsa >/dev/null 2>&1 ; then
#elif [ -x /usr/bin/amixer ]; then
	# alsa audio volume control
	case "$1" in
	inc)	amixer -q set Master 5%+ ;;
	dec)	amixer -q set Master 5%+ ;;
	mute)	amixer set Master toggle ;;
	play)	play -q "$2" & ;;
	esac
fi

