#!/bin/sh

uname=nikosc

usermod -aG audio $uname
usermod -aG socklog $uname
usermod -aG video $uname
usermod -aG wireshark $uname
usermod -aG input $uname
usermod -aG kvm $uname

#sudoedit /etc/sudoers
apt -e alsa acpid sshd sndiod smartd uuidd
apt -e bluetoothd

apt -e socklog-unix nanoklogd

# edit /etc/ssh/sshd_config
# remove RootPermit
