#!/bin/sh

uname=nikosc
if [ ! -d /home/$uname ]; then
	useradd -m $uname
fi
usermod -aG audio,video $uname
usermod -aG wireshark $uname
usermod -aG input $uname
usermod -aG kvm $uname
usermod -aG bluetooth $uname

groupadd sshusers
usermod -aG sshusers $uname

./app -e metalog
./app -e alsa acpid sshd sndiod uuidd
./app -e bluetoothd
./app -e avahi-daemon avahi-dnsconfd

echo "add user to sudoers: sudoedit /etc/sudoers"




