#!/bin/sh

uname=nikosc

usermod -aG audio $uname
usermod -aG socklog $uname
usermod -aG video $uname
usermod -aG wireshark $uname

#sudoedit /etc/sudoers
apt -e alsa acpid sshd sndiod smartd uuidd
apt -e bluetoothd

