#!/bin/tcsh -f

# install generic scripts
cd local-bin  && ./install.sh && cd ..
cd local-sbin && ./install.sh && cd ..

# fix JED installation path
if ( ! -d /usr/share/jed ) then
	mkdir /usr/share/jed
endif
if ( ! -l /usr/jed ) then
	ln -s /usr/share/jed /usr/jed
endif

#
if ( ! -f /etc/complete.tcsh ) then
	cp misc/complete.tcsh /etc
endif

# install configuration files
./install-nano-syntax-files
./install-to-users .tcshrc .login .bashrc .mkshrc .bin .help \
	.jed .nanorc .grief-local .grinit .joerc \
	.newsboat .clogrc \
	.gitconfig .config .xres \
	.dof .conkyrc .bc .tmux.conf .vimrc .a2ps .abook

# rsync
if ( -d /srv/file-server ) then
	cp fserv-sync /srv/file-server
endif

# various data files
cd icons      && ./install.sh && cd ..
cd wallpapers && ./install.sh && cd ..
cd sounds     && ./install.sh && cd ..

# post-install scripts
local-sbin/enable-bitmap-fonts


