#!/bin/tcsh -f

set echo_style=both
foreach file ( .tcshrc .mkshrc .login .Xresources .nanorc .jed .help .emacs .emacs.d .joerc .xres .themes .icons .fonts .bc .procmailrc .fetchmailrc .msmtprc .msmtp.log .gitconfig .muttrc )
	set src = $file
	if ( ! -e $src ) set src = dotfiles/$file
	if ( ! -e $src ) set src = /root/$file

	echo "$src"
	cp -r $src /root
	foreach dir ( /home/* )
		set name = $dir:t
		cp -r $src $dir
		chown -R ${name}:${name} $dir/${src:t}
		chmod -R 0600 $dir/${src:t}
		chmod -R u+X $dir/${src:t}
	end
end


