#!/bin/tcsh -f

set echo_style=both
foreach file ( .tcshrc .mkshrc .login .nanorc\
				.jed .help .emacs .emacs.d .joerc\
				.Xresources .xres .themes .icons .fonts\
				.bc .gitconfig .abook .newsboat )
	set src = $file
	if ( ! -e $src ) set src = dotfiles/$file
	if ( ! -e $src ) set src = /root/$file
	if ( ! -e $src ) continue

	echo "$src"
	cp -r $src /root
	foreach dir ( /home/* )
		set name = $dir:t
		cp -r $src $dir
		chown -R ${name}:${name} $dir/${src:t}
		if ( $file == ".help" || $file == ".bin" ) then
			chmod -R 0700 $dir/${src:t}
		else
			chmod -R 0600 $dir/${src:t}
		endif
		chmod -R u+X $dir/${src:t}
	end
end
install -m 755 local-bin/* /usr/local/bin/
./install-nano-syntax-files
echo "copy .config manually"
echo "copy .doc-templates and .wallpapers manually"
echo "mail files does not copied"

