#!/bin/tcsh -f
#
#	copies the .tcshrc to all users of the system
#

set echo_style=both
set src = .jed
if ( ! -e $src ) set src = dotfiles/.jed
if ( ! -e $src ) set src = /root/.jed

echo "root\t$src -> /root"
cp -r $src /root
foreach dir ( /home/* )
	set name = $dir:t
	echo "$name\t$src -> $dir"
	cp -r $src $dir
	chown -R ${name}:${name} $dir/${src:t}
end


