#!/bin/csh -f
# Ειδοποίηση (ομιλία) ότι έφτασε ταχυδρομείο...
set text=""
if ( "$1" != "0" ) then
	if ( "$1" == "" ) then
		set text="νέα μυνήματα."
	else
		if ( "$1" == "1" ) then
			set text="ένα νέο μύνημα."
		else
			set text="$1 νέα μυνήματα."
		endif
	endif
endif
say $text
