#!/bin/sh
if [ -d /etc/skel ]; then
	cp -r .xfce4-autoexec .bin .help .config\
		.tcshrc .bashrc .environ .aliases\
		.ksh88rc .ksh93rc .kshrc .profile .mkshrc .yashrc .ashrc\
		.mostrc\
		.tmux .tmux.conf\
		.urxvt .xres .Xresources\
		.jed .nanorc .newsboat .bc\
		/etc/skel/
fi
