#!/bin/tcsh -f
#
#	copies the .tcshrc to all users of the system
#

set echo_style=both
set src = .tcshrc
if ( ! -e $src ) set src = dotfiles/.tcshrc
if ( ! -e $src ) set src = /root/.tcshrc

echo "root\t$src -> /root"
cp $src /root
foreach dir ( /home/* )
	set name = $dir:t
	echo "$name\t$src -> $dir"
	cp $src $dir
	chown ${name}:${name} $dir/${src:t}
end


