#!/bin/sh
if [ -d /etc/skel ]; then
	cp -r .xfce4-autoexec .bin .help .config\
		.tcshrc .bashrc .zshrc .environ .aliases\
		.mostrc\
		.tmux .tmux.conf\
		.urxvt .xres .Xresources\
		.jed .nanorc .newsboat .bc\
		/etc/skel/
fi
