#!/bin/tcsh -f

set echo_style=both

foreach file ( .tcshrc .login )
	set src = $file
	if ( ! -e $src ) set src = dotfiles/$file
	if ( ! -e $src ) set src = /root/$file
	if ( ! -e $src ) exit 1

	echo "root\t$src -> /root"
	cp -r $src /root
	foreach dir ( /home/* )
		set name = $dir:t
		echo "$name\t$src -> $dir"
		cp -r $src $dir
		chmod 0600 $dir/$file
		chown ${name}:${name} $dir/$file
	end
end


