#!/bin/tcsh

set info  = "\033[1;32m"
set reset = "\033[0m"

if ( $# > 0 ) then
	set src = "$1"
else
	# change src to local repository
	set src = '/usr/src/dotfiles'
endif
# change 'user' to your catalog 
set dst = `echo $src | sed 's%/usr/src/dotfiles%/home/user%'`
#echo "${info}=== scanning $src${reset}"

@ cnt = 0
foreach s ( $src/{.*,*} )
	set file = $s:t
	if ( $file == "." || $file == ".." || $file == ".git" || $file == ".gitignore" ) then
		continue
	endif
	if ( -e "$s" ) then
		if ( -d "$s" ) then
			$0 $s
			continue
		endif
	
		set d = $dst/$file
		if ( -M "$d" > -M "$s" ) then
			echo "cp $d -> $s"
			cp "$d" "$s"
			@ cnt ++
		endif
	endif
end

if ( $src == '/usr/src/dotfiles' ) then
	if ( $cnt > 0 ) then
		echo "${info}Files changed, update git${reset}"
		git add .
		git commit -m "automatic update"
		git push
	endif
endif


