#!/bin/sh
# usage: extract <file>

if [ "$1" = "--help" -o "$1" = "-h" -o "$1" = "" ]; then
	echo "usage: extract <file> ..."
	exit 1
fi

for f in $@; do
	if [ -f "$f" ] ; then
		case "$f" in
		*.tar.bz2)   tar xjf "$f"   ;;
		*.tar.gz)    tar xzf "$f"   ;;
		*.bz2)       bunzip2 "$f"   ;;
		*.rar)       unrar x "$f"   ;;
		*.gz)        gunzip "$f"    ;;
		*.tar)       tar xf "$f"    ;;
		*.tbz2)      tar xjf "$f"   ;;
		*.tgz)       tar xzf "$f"   ;;
		*.zip)       unzip "$f"     ;;
		*.Z)         uncompress "$f";;
		*.7z)        7z x "$f"      ;;
		*.deb)       ar x "$f"      ;;
		*.tar.xz)    tar xf "$f"    ;;
		*.tar.zst)   unzstd "$f"    ;;      
		*)           echo "'$f' cannot be extracted" ;;
		esac
	else
		echo "'$f' is not a valid file"
	fi
done
