#!/bin/tcsh -f

#
#	notification for mailer
#	it says "you have n new messages"
#

set text=""
if ( "$1" != "0" ) then
	if ( "$1" == "" ) then
		set text="νέα μυνήματα."
	else
		if ( "$1" == "1" ) then
			set text="ένα νέο μύνημα."
		else
			set text="$1 νέα μυνήματα."
		endif
	endif
	speak $text
endif

