#!/bin/tcsh -f
# tui-prompt "message..." "command"
if ( -X smenu ) then
	if ( `printf "No\\nYes" | smenu -m "$1"` == "Yes" ) then
		$2
	endif
else
	dialog --title "Message" --yesno "$1" 6 25 && $2
endif

