#!/bin/sh
#
#	Message-Of-The-Day update system
#

# final file
FILE="/etc/motd"

# directory of MOTD scripts
MDIR="/etc/motd.d"

# create motd
if [ -f $FILE ]; then
	rm $FILE
fi
for f in $MDIR/*; do
	if [ -x $f ]; then
		$f >> $FILE
	fi
done

cat $FILE
