#!/bin/sh

FILE="/etc/motd"

rm $FILE

# header
if [ -f /etc/motd-head ]; then
	cat motd-head  >> $FILE
else
#	echo -n "\033[1m\033[32m" >> $FILE
	echo -n "=============================" >> $FILE
	echo -n " Message Of The Day " >> $FILE
	echo -n "=============================" >> $FILE
#	echo "\033[0m" >> $FILE
	echo >> $FILE
	echo >> $FILE
fi

# quote
if [ -f /etc/motd-quote ]; then
	cat motd-quote >> $FILE
else
	echo -n "\033[36m" >> $FILE
	fortune diogenis >> $FILE
	echo "\033[0m" >> $FILE
fi

# admin's message queue
if [ -f /etc/motd-queue ]; then
	cat motd-quote >> $FILE
else
	uname -a >> $FILE
	date >> $FILE
fi

# footer
if [ -f /etc/motd-tail ]; then
	cat motd-tail >> $FILE
else
	echo "\033[0m" >> $FILE
fi


