#!/bin/sh
f=`echo $1 | sed 's/_/-/g'`
lynx -dump -nolist http://www.php.net/manual/en/print/function.$f.php \
	| sed -n /^$1/,/^.*User\ Contributed\ Notes/p \
	| grep -v 'add a note' \
	| grep -v 'User\ Contributed\ Notes'
