scriptencoding utf-8
set nocompatible
set tabstop=4
"if !has('gui_running')
"	set t_Co=256
"endif

" General
set number	" Show line numbers
"set no wrap	" Wrap lines
set textwidth=132 " Line wrap (number of cols)
set showmatch	" Highlight matching brace
"set spell spelllang=en,el	" Enable spell-checking
set nospell
set virtualedit=insert	" Enable free-range cursor
set errorbells	" Beep or flash screen on errors
set visualbell	" Use visual bell (no beeping)

set hlsearch	" Highlight all search results
set smartcase	" Enable smart-case search
set ignorecase	" Always case-insensitive
set incsearch	" Searches for strings incrementally

set autoindent	" Auto-indent new lines
"set noautoindent
set shiftwidth=4	" Number of auto-indent spaces
set smartindent	" Enable smart-indent
set smarttab	" Enable smart-tabs
set softtabstop=4	" Number of spaces per Tab
set noexpandtab
set terse

" Advanced
set ruler	" Show row and column ruler information
set showmatch
set matchtime=3

" backup
if !isdirectory($HOME."/.backup/text")
	silent! execute "!mkdir -p ~/.backup/text"
endif
set backup
set backupdir=~/.backup/text
" not generate .swap
set noswapfile

"
set undolevels=1000	" Number of undo levels
set backspace=indent,eol,start	" Backspace behaviour

syntax on
filetype on
filetype plugin on

" -----------------------------------
" extra packages

runtime! ftplugin/man.vim
packadd! reedline.vim
packadd! ctrlp.vim
packadd! vim-quickui

packadd! lightline.vim
"set noshowmode

packadd! vim-commentor
command! CommentBlock	:call commentor#CommentToggle(visualmode(), 1)
" on select mode press gc to (un)comment block

"packadd! vim-lastplace

let g:workspace_session_directory = $HOME . '/.vim/sessions/'
let g:workspace_session_disable_on_args = 1
let g:workspace_autosave_always = 1
packadd! vim-workspace
" Use :ToggleWorkspace of there is no auto-session

" -----------------------------------
" colors
packadd! borland
" onedark turbo borland
colorscheme borland

" -----------------------------------

" fix ALT keys mapping
source ~/.vim/altkeys.vim

" load default BRIEF emulation
source ~/.vim/brief.vim

" my BRIEF's version
source ~/.vim/ndc-brief.vim

" -----------------------------------

" Markdown files
au BufRead,BufNewFile *.md setlocal filetype=markdown
" Treat all .tex files as latex
au BufRead,BufNewFile *.tex setlocal filetype=tex
" LaTeX class files
au BufRead,BufNewFile *.cls setlocal filetype=tex
" SQLite-specific file
au BufRead,BufNewFile *.sqlite setlocal filetype=sql
" Treat all .h files as C (not cpp)
au BufRead,BufNewFile *.h setlocal filetype=c

" enable spell on simple docs
autocmd FileType markdown,text,pandoc,tex setlocal spell spelllang=en,el


