#!/bin/bash

# LC = local
allow=(LC GR CY)
iprcnt=/proc/net/xt_recent

#
list=`cat $iprcnt/CHECKIP | awk '/src=/ { print substr($1,5) }'`
for e in $list; do
	geoinfo=$(geoiplookup "$e" | head -n 1 | awk -F ": " '{print$2}')
	if [[ $geoinfo =~ ^.*not\ found$ ]]; then
		country="LC"
	else
		country=$(echo "$geoinfo" | awk -F "," '{ print $1 }')
	fi
	found=n
	for cc in $allow; do
		if [[ $cc == $country ]]; then
			found=y
		fi
	done
	if [[ $found == "y" ]]; then
		logger -t "BANLIST" "$e $geoinfo"
		echo "+$e" > $iprcnt/BANLIST
		echo "-$e" > $iprcnt/CHECKIP
	fi
done


