#!/bin/bash
#
#	NetBSD packages for Linux
#		https://www.pkgsrc.org/
#
#	The list of the packages by category
#		http://cdn.netbsd.org/pub/pkgsrc/current/pkgsrc/README.html
#

#
DIR=$PWD
SH=/bin/bash
export SH
PKGSRC_ROOT=/usr/src
cd $PKGSRC_ROOT

#
PKG_PATH="http://cdn.NetBSD.org/pub/pkgsrc/packages/$(uname -s)/$(uname -m)/$(uname -r|cut -f '1 2' -d.)/All/"
export PKG_PATH

# download the repo
cvs -danoncvs@anoncvs.netbsd.org:/cvsroot checkout pkgsrc
cd pkgsrc/bootstrap

# run bootstrap
if [ -d /usr/src/pkgsrc/bootstrap/work ]; then
	rm -r /usr/src/pkgsrc/bootstrap/work
fi
unset PKG_PATH
unset MAKEFLAGS
./bootstrap

# copy the update script
cp $DIR/update-pkgsrc /usr/pkg/bin

#
# that's all
# now go to package and make it
#
#	example:
#		cd pkgsrc/devel/memcached
#		make install clean
#
