#!/bin/sh

if [ ! -z "$1" ]; then
	if [[ "$1" == "start" ]]; then
		pulseaudio --system -D
	elif [[ "$1" == "stop" ]]; then
		pulseaudio -k
	elif [[ "$1" == "restart" ]]; then
		pulseaudio -k && sleep 2
		pulseaudio --system -D
	else
		echo "unknown parameter $1"
		exit 1
	fi
else
	pulseaudio --system -D
fi

