#!/bin/sh

list=""
list="$list https://github.com/suve/fpman"
for s in $list; do
	p=$(basename $s)
	if [ -d $p/.git ]; then
		cd $p
		git pull
		cd ..
	else
		git clone $s
	fi
done

cd fpman/src
fpc -XS fpman
if [ -d ~/.bin ]; then
	cp fpman ~/.bin
	sudo cp fpman.man /usr/local/share/man/man1/fpman.1
else
	sudo cp fpman /usr/local/bin
	sudo cp fpman.man /usr/local/share/man/man1/fpman.1
fi
cd ../..

#[ ! -d fpman-doc ] && mkdir fpman-doc
#if [ ! -e fpman-doc/doc-html.zip ]; then
#	cd fpman-doc
#	wget -O doc-html.zip "https://downloads.sourceforge.net/project/freepascal/Documentation/3.2.0/doc-html.zip?r=https%3A%2F%2Fsourceforge.net%2Fprojects%2Ffreepascal%2Ffiles%2FDocumentation%2F3.2.0%2Fdoc-html.zip%2Fdownload&ts=1607807857"
#fi

if [ ! -d ~/.suve/fpman ]; then
	mkdir ~/.suve
	mkdir ~/.suve/fpman
fi
cp -r fpman/pages/* ~/.suve/fpman/
fpman --rebuild
#cd fpman-doc
#rm -rf doc
#unzip doc-html.zip
#cd ..
#fpman --import fpman-doc/doc
