#!/bin/tcsh -f
#
#	Package and service manager for Void/Ubuntu/Slackware/Manjaro Linux
#
#	Copyright (C) 2019, Nicholas Christopoulos <nereus@freemail.gr>
#
#	This program is free software; you can redistribute it and/or modify it
#	under the terms of the GNU General Public License as published by the Free
#	Software Foundation; either version 3 of the License, or (at your option)
#	any later version.
#

###
set todo = help
if ( $#argv > 0 ) then
	set todo = $1
endif

switch ( $todo )
#
#	basic package utilities
#
case -i:
case install:
	apt install $argv[2-]
	breaksw
case -r:
case remove:
	apt remove $argv[2-]
	breaksw
case reinstall:
	apt reinstall $argv[2-]
	breaksw
case -u:
case update:
	apt update && apt upgrade
#	updatedb
	breaksw

#
#	advanced package utilities
#
case -v:
case info:
case show:
case view:
	apt show $argv[2-]
	breaksw

case -s:
case search:
	apt search $argv[2-]
	breaksw

case -rs:
case regex-search:
	apt search $argv[2-]
	breaksw

case -f:
case -fs:
case file-search:
	breaksw

case --files:
	dpkg -L $argv[2-]
	breaksw

#
#	services
#
case -e:
case -es:
case enable:
case enable-service:
	foreach o ( $argv[2-] )
		update-rc.d $o enable
	end
	breaksw

case -d:
case -ds:
case disable:
case disable-service:
	foreach o ( $argv[2-] )
		update-rc.d $o disable
	end
	breaksw

case start:
case stop:
case status:
case restart:
	foreach f ( $argv[2-] )
		switch ( $f )
		case avahi:
			set service = avahi-daemon
			breaksw
		case nfs:
		case nfsd:
			set service = nfs-server
			breaksw
		case samba:
		case smb:
			set service = smbd
			breaksw
		default:
			set service = $f
		endsw
		/etc/init.d/$service $todo
	end
	breaksw

case -ld:
case -lds:
case -av:
case list-disabled:
case avail:
	breaksw

case -le:
case -les:
case -nav:
case list-enabled:
	breaksw

case -o:
case autoremove:
	apt autoremove
	set tmp = /tmp/autopurge.tmp
	dpkg -l | awk '/^rc/ {print $2}' > $tmp
	set n = `cat $tmp | wc -l`
	echo "Autopurge: $n packages to be cleaned"
	if ( $n > 0 ) then
		cat $tmp | xargs sudo dpkg --purge
	endif
	rm $tmp
	apt-get auto-clean
	breaksw

case -rc:
case reconfigure:
	dpkg-reconfigure -f $argv[2-]
	breaksw

help:
default:
	cat <<EOF
Package and service manager for Void Linux, version 1.1

Packages:
    -i  | install ...             install package[s]
    -r  | remove ...              remove package[s]
    -u  | update ...              update package list and upgrade all installed packages
    reinstall ...                 reinstall package[s]
    -s  | search <pattern>        search for packages by matching package-name
    -v  | show | info | view ...  display information about package[s]
    -f  | file-search ...         search file in packages
    --files <package>             show files of specific package

Services:
    -e[s]  | enable[-service] <service>
    -d[s]  | disable[-service] <service>
#    -le[s] | -nav | list-enabled  display all actived services
#    -ld[s] | -av | list-disabled  display all available (disabled) services
    start | stop | restart | status <service>

Special:
    -o  | autoremove              remove obsolete packages
    -rc | reconfigure <package>

EOF
endsw


