#!/bin/sh

if [ $# -lt 1 ]; then
	echo "Usage : $0 [{inc|dec|mute}] [play file]"
	exit 1
fi
if [ $# -gt 1 ]; then
	par="$2"
fi

if pgrep pulseaudio > /dev/null 2>&1 ; then
	# pulse audio volume control
	case "$1" in
	inc)
		par=${par-10}	
		pactl set-sink-volume 0 -- "+${par}%" ;;
	dec)
		par=${par-10}	
		pactl set-sink-volume 0 -- "-${par}%" ;;
    get)	amixer get Master | grep '%' | head -n 1 | cut -d '[' -f 2 | cut -d '%' -f 1 ;;
	set)
		par=${par-100}
		pactl set-sink-volume 0 -- "${par}%" ;;
	mute)	pactl set-sink-volume 0 0 ;;
	play)	paplay "$2" & ;;
	esac
elif pgrep sndiod >/dev/null 2>&1 ; then
	# sndio audio volume control
	case "$1" in
	inc)
		par=${par-10}
		nn=$((par*127/100))
		aucatctl master=$(($(aucatctl | grep master | cut -f2 -d=)+$nn)) ;;
	dec)
		par=${par-10}
		nn=$((par*127/100))
		aucatctl master=$(($(aucatctl | grep master | cut -f2 -d=)-$nn)) ;;
	set)
		par=${par-100}
		nn=$((par*127/100))
		aucatctl master=$nn ;;
    get)	amixer get Master | grep '%' | head -n 1 | cut -d '[' -f 2 | cut -d '%' -f 1 ;;
	mute)	aucatctl master=0 ;;
	play)	play -q "$2" & ;;
	esac
elif pgrep alsa >/dev/null 2>&1 ; then
#elif [ -x /usr/bin/amixer ]; then
	# alsa audio volume control
	case "$1" in
	inc)
		par=${par-10}
		amixer -q set Master "${par}%+" ;;
	dec)
		par=${par-10}
		amixer -q set Master "${par}%-" ;;
	mute)
		amixer set Master toggle ;;
	set)
		par=${par-100}
		amixer -q set Master "${par}%" ;;
    get)	amixer get Master | grep '%' | head -n 1 | cut -d '[' -f 2 | cut -d '%' -f 1 ;;
	play)	play -q "$2" & ;;
	esac
fi

