#!/bin/sh

uname=nikosc
if [ ! -d /home/$uname ]; then
	useradd -m $uname
fi
usermod -aG audio,video,pulse,rtkit,pulse-access root
usermod -aG audio,video,pulse,rtkit,pulse-access $uname
#usermod -aG wireshark $uname
usermod -aG input $uname
usermod -aG kvm $uname
usermod -aG bluetooth $uname
usermod -aG wheel $uname

./app -e rsyslogd
./app -e alsa acpid sshd pulseaudio uuidd
./app -e bluetoothd
./app -e avahi-daemon avahi-dnsconfd

echo "add user to sudoers: sudoedit /etc/sudoers; @wheel must be enabled"




