#!/bin/sh

if pgrep -x xfce4-session > /dev/null
  then
  export DISPLAY=:0
  export XAUTHORITY="/home/alex/.Xauthority"
  exec snooze -w0 -H/6 -t /home/alex/.snooze/updater \
    chpst -u alex:alex /usr/local/bin/void-scripts/void-updater.sh
else
  sleep 5m
  sv reload void-updater
fi
