#!/bin/sh

if [ ! -d ~/.bin/.games ]; then
	mkdir ~/.bin/.games
fi
games=$(ls ~/.bin/.games/)
for f in $games; do
	echo $f
	if [ "$1" = "$f" ]; then
		. ~/.bin/.games/$f
		pgrep wineserver && wineserver -k
		if [ -d "$dir" ]; then
			cd "$dir"
			exec wine "$exe"
			#pgrep wineserver && wineserver -k
		else
			echo "the game's [$dir] directory does not exists"
			exit 1
		fi
	fi
done



