#!/bin/sh
DISTRO=$( grep '^ID=' /etc/os-release | awk 'BEGIN{FS="=";}{print $2}' | sed s/\"//g )

scale=1.333
if [ -x /opt/viber/Viber ]; then
	method=n
elif [ -x /opt/viber.AppImage ]; then
	method=a
else
	method=f
fi

while getopts afnhs: o; do
	case "$o" in
	h)
		echo "usage: viber [-h|-n|-a|-f] [-s factor]"
		echo "-n        ... native version"
		echo "-a        ... appimage version"
		echo "-f        ... flatpak version"
		echo "-s factor ... zoom scaling factor"
		echo "-h        ... this screen"
		echo "default method=$method with scaling=$scale"
		exit 1
		;;
	s)	scale="$OPTARG";;
	n)	method=n;;
	a)	method=a;;
	f)	method=f;;
	esac
done

[ "$method" = "n" ] && QT_SCALE_FACTOR=$scale /opt/viber/Viber $@ &
[ "$method" = "a" ] && QT_SCALE_FACTOR=$scale /opt/viber.AppImage $@ &
[ "$method" = "f" ] && QT_SCALE_FACTOR=$scale flatpak run com.viber.Viber $@ &


