#!/bin/tcsh -f

set todo = def
if ( $#argv > 1 ) then
	set todo = $1
endif
switch ( $todo )
case i:
	slackpkg install $argv[2-]
	breaksw
case u:
	slackpkg update && slackpkg upgrade-all && slackpkg install-new
	breaksw
case restart:
	set prg = $2
	switch ( $prg )
	case apache:
	case httpd:
	case http:
	case apache2:
		/etc/rc.d/rc.httpd restart
		breaksw
	case smbd:
	case smb:
	case samba:
		/etc/rc.d/rc.samba restart
		breaksw
	case avahi:
	case mdns:
		/etc/rc.d/rc.avahi restart
		breaksw
	case nfs:
	case nfsd:
		/etc/rc.d/rc.nfsd restart
		breaksw
	default:
		/etc/rc.d/rc.$prg restart
	endsw
	breaksw
case show:
	slackpkg info $argv[2-]
	breaksw
default:
	slackpkg $*
endsw

