#!/bin/sh
if [ -e /etc/fonts/conf.d/70-no-bitmaps.conf ]; then
	sudo rm /etc/fonts/conf.d/70-no-bitmaps.conf
fi
if [ ! -e /etc/fonts/conf.d/70-yes-bitmaps.conf ]; then
	if [ -e /etc/fonts/conf.avail/70-yes-bitmaps.conf ]; then
		sudo ln -s /etc/fonts/conf.avail/70-yes-bitmaps.conf /etc/fonts/conf.d/70-yes-bitmaps.conf
	fi
fi


