#!/bin/sh

# get default parameter ("help" for none)
todo=help

# available options
opts=$(cat /sys/power/state)

#
if [ $# -gt 0 ]; then
	todo="$1"

	# is known?
	for o in $opts; do
		if [ "$todo" = "$o" ]; then
			# found; execute it
			exec echo -n $todo > /sys/power/state
		fi
	done
	echo "unknown state [$todo]; only [$opts] are available"
	exit 1
fi

# print help and exit
echo "usage: $0 [option]"
echo "available options on kernel: $opts"


