#!/bin/tcsh -f
# -*- mode: shell -*-

# get default parameter ("help" for none)
set todo = help

# available options
set opts = `cat /sys/power/state`

if ( $#argv > 0 ) then
	set todo = $argv[1]

	# is known?
	foreach o ( $opts )
		if ( $todo == $o ) then
			# found; execute it
			echo -n $todo > /sys/power/state
			exit 0
		endif
	end
endif

# print help and exit
echo "usage: $0 [option]"
echo "available options on kernel: $opts"


