#!/bin/tcsh -f
#
#	Package and service manager for *BSD
#
#	Copyright (C) 2019, Nicholas Christopoulos <nereus@freemail.gr>
#
#	This program is free software; you can redistribute it and/or modify it
#	under the terms of the GNU General Public License as published by the Free
#	Software Foundation; either version 3 of the License, or (at your option)
#	any later version.
#

###
set todo = help
if ( $#argv > 0 ) then
	set todo = $1
endif

switch ( $todo )
#
#	basic package utilities
#
case -i:
case install:
	pkg_add -iv $argv[2-]
	breaksw
case -r:
case remove:
	pkg_delete $argv[2-]
	breaksw
case reinstall:
	pkg_delete $argv[2-]
	pkg_add -iv $argv[2-]
	breaksw
case -u:
case update:
	pkg_add -u
	breaksw

#
#	advanced package utilities
#
case -v:
case info:
case show:
case view:
#	pkg_info -m $argv[2-]
	breaksw

case -s:
case search:
	pkg_info -Q $argv[2-]
	breaksw

case -rs:
case regex-search:
	pkg_info -Q $argv[2-]
	breaksw

case -f:
case -fs:
case file-search:
	pkg_info -qE $argv[2-]
	breaksw

#
#	services
#
case -e:
case -es:
case enable:
case enable-service:
	breaksw

case -d:
case -ds:
case disable:
case disable-service:
	breaksw

case start:
case stop:
case status:
case restart:
	breaksw

case -ld:
case -lds:
case -av:
case list-disabled:
case avail:
	breaksw

case -le:
case -les:
case -nav:
case list-enabled:
	breaksw

case -o:
case autoremove:
	breaksw

case -rc:
case reconfigure:
	breaksw

case -rok:
case remove-old-kernels:
	breaksw

case --files:
	pkg_info -L $argv[2-]
	breaksw

help:
default:
	cat <<EOF
Package and service manager for Void Linux, version 1.1

Packages:
    -i  | install ...             install package[s]
    -r  | remove ...              remove package[s]
    -u  | update ...              update package list and upgrade all installed packages
    reinstall ...                 reinstall package[s]
    -s  | search <pattern>        search for packages by matching package-name
#    -v  | show | info | view ...  display information about package[s]
    -f  | file-search ...         search file in packages

Services:
#    -e[s]  | enable[-service] <service>
#    -d[s]  | disable[-service] <service>
#    -le[s] | -nav | list-enabled  display all actived services
#    -ld[s] | -av | list-disabled  display all available (disabled) services
#    start | stop | restart | status <service>

Special:
#    -o   | autoremove              remove obsolete packages
#    -rc  | reconfigure <package>
#    -rok | remove-old-kernels
    --files <package>              shows the files of the package

EOF
endsw

