#!/bin/tcsh -f
#
#	Package and service manager for Manjaro
#
#	Copyright (C) 2019, Nicholas Christopoulos <nereus@freemail.gr>
#
#	This program is free software; you can redistribute it and/or modify it
#	under the terms of the GNU General Public License as published by the Free
#	Software Foundation; either version 3 of the License, or (at your option)
#	any later version.
#

###
set todo = help
if ( $#argv > 0 ) then
	set todo = $1
endif

switch ( $todo )
#
#	basic package utilities
#
case -i:
case install:
	pacman -S $argv[2-]
	breaksw
case -r:
case remove:
	pacman -R $argv[2-]
	breaksw
case reinstall:
	echo "not supported"
	breaksw
case -u:
case update:
	pacman -Su $argv[2-]
	breaksw
case -s:
case search:
	pacman -Ss $argv[2-]
	breaksw
case -v:
case info:
case view:
case show:
	pacman -Qi $argv[2-]
	breaksw
case -f:
case file-search:
case search-file:
	pacman -Fy $argv[2-]
	breaksw
case --files:
case files:
	pacman -Ql $argv[2-]
	breaksw
#
#	services
#
case start:
case stop:
case restart:
	systemctl $1 $argv[2-]
	breaksw
case -e:
case enable:
	systemctl enable $argv[2-]
	breaksw
case -d:
case disable:
	systemctl disable $argv[2-]
	breaksw

help:
default:
	cat <<EOF
Package and service manager for Arch/Manjaro Linux, version 1.1

Packages:
    -i  | install ...             install package[s]
    -r  | remove ...              remove package[s]
    -u  | update ...              update package list and upgrade all installed packages
#    reinstall ...                 reinstall package[s]
    -s  | search <pattern>        search for packages by matching package-name
    -v  | show | info | view ...  display information about package[s]
    -f  | file-search ...         search file in packages

Services:
    -e[s]  | enable[-service] <service>
    -d[s]  | disable[-service] <service>
#    -le[s] | -nav | list-enabled  display all actived services
#    -ld[s] | -av | list-disabled  display all available (disabled) services
    start | stop | restart | status <service>

Special:
#    -o   | autoremove              remove obsolete packages
#    -rc  | reconfigure <package>
#    -rok | remove-old-kernels
    --files <package>               shows the files of the package

EOF
endsw


