#!/bin/sh
# Copyright 1999, 2002, 2012  Patrick Volkerding, Moorhead, Minnesota USA
# All rights reserved.
#
# Redistribution and use of this script, with or without modification, is
# permitted provided that the following conditions are met:
#
# 1. Redistributions of this script must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#
#  THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR IMPLIED
#  WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
#  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO
#  EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
#  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
#  PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
#  OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
#  WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
#  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
#  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#

xidir=/etc/X11/xinit-nc

# First, let's bail if our being here doesn't make sense:
if [ ! -d $xidir ]; then
  exit 1
fi
if [ "`cd $xidir ; echo *.*`" = '*.*' ]; then
  exit 1
fi

if [ "$USER" = "root" ]; then
  TMP=/var/log/setup/tmp
else
  TMP=$HOME/.xwmconfig
fi

if [ ! -d $TMP ]; then
 mkdir -p $TMP
 chmod 700 $TMP
fi

# Do we already have an existing default?
unset PRESELECT
if [ -L $xidir/xinitrc ]; then
  CURRENT="$xidir/xwmlist -s"
  PRESELECT=" --default-item $CURRENT "
fi

# Figure out who we are and set up some background information:
if [ "$USER" = "root" ]; then
  BACKTITLE="--backtitle \"Setting system-wide default window manager in $xidir/\""
else
  BACKTITLE="--backtitle \"Setting default window manager in $HOME/.xinitrc and $HOME/.xsession\""
fi

# This stops --backtitle from cluttering the initial install:
if [ ! -r /proc/kcore ]; then
  BACKTITLE=""
fi

# Remove any previous script:
rm -f $TMP/tmpscript.sh

# Add the top of the script:
if [ -r $xidir/xinitrc.gnome -a -r $xidir/xinitrc.kde ]; then
cat << EOF > $TMP/tmpscript.sh
#!/bin/sh
dialog $BACKTITLE --title "SELECT DEFAULT WINDOW MANAGER FOR X" $PRESELECT --menu \\
"Please select the default window manager to use with the X Window \\
System. This will define the style of graphical user interface \\
the computer uses. KDE and GNOME provide the most features. People \\
with Windows or MacOS experience will find either one easy to use. \\
Other window managers are easier on system \\
resources, or provide other unique features." 12 74 0 \\
EOF
elif [ -r $xidir/xinitrc.kde ]; then 
cat << EOF > $TMP/tmpscript.sh
#!/bin/sh
dialog $BACKTITLE --title "SELECT DEFAULT WINDOW MANAGER FOR X" $PRESELECT --menu \\
"Please select the default window manager to use with the X Window \\
System. This will define the style of graphical user interface \\
the computer uses. KDE provides the most features, and people \\
with Windows or MacOS experience will find it easy to use. \\
Other window managers are easier on system \\
resources, or provide other unique features." 12 74 0 \\
EOF
elif [ -r $xidir/xinitrc.xfce ]; then
cat << EOF > $TMP/tmpscript.sh
#!/bin/sh
dialog $BACKTITLE --title "SELECT DEFAULT WINDOW MANAGER FOR X" $PRESELECT --menu \\
"Please select the default window manager to use with the X Window \\
System. This will define the style of graphical user interface \\
the computer uses. XFce provides the most features, and people \\
with Windows or MacOS experience will find it easy to use. \\
Other window managers are easier on system \\
resources, or provide other unique features." 12 74 0 \\
EOF
else
cat << EOF > $TMP/tmpscript.sh
dialog $BACKTITLE --title "SELECT DEFAULT WINDOW MANAGER FOR X" $PRESELECT --menu \\
"Please select the default window manager to use with the X Window \\
System. This will define the style of graphical user interface \\
the computer uses." 12 74 0 \\
EOF
fi

$xidir/xwmlist -x >> $TMP/tmpscript.sh

# Then, the tail end:
cat << EOF >> $TMP/tmpscript.sh
2> $TMP/output
if [ ! \$? = 0 ]; then
  rm -f $TMP/output
  echo "Canceled."
  exit
fi
EOF

sh $TMP/tmpscript.sh

if [ ! -r $TMP/output ]; then
  rm -f $TMP/tmpscript.sh
  exit
fi

OUTPUT=`cat $TMP/output`

# If xwmconfig is run by root, it changes the system-wide default for users
# that do not have a $HOME/.xinitrc:
if [ "$USER" = "root" ]; then
  if [ -r $xidir/$OUTPUT ]; then
    ( cd $xidir ; rm -f conf ; ln -sf $OUTPUT conf )
  fi
fi

# Also set up a new $HOME/.xinitrc and $HOME/.xsession:
if [ -r $xidir/$OUTPUT -a ! "$HOME" = "/" ]; then
  if [ -r $HOME/.xinitrc ]; then
    rm -f $HOME/.xinitrc-backup
    mv $HOME/.xinitrc $HOME/.xinitrc-backup
  fi
	echo "#!/bin/sh" > $HOME/.xinitrc
	cat $xidir/$OUTPUT >> $HOME/.xinitrc
	cat $xidir/xinitrc >> $HOME/.xinitrc
  if [ -r $HOME/.xsession ]; then
    rm -f $HOME/.xsession-backup
    mv $HOME/.xsession $HOME/.xsession-backup
  fi
	echo "#!/bin/sh" > $HOME/.xsession
	cat $xidir/$OUTPUT >> $HOME/.xsession
	cat $xidir/xinitrc >> $HOME/.xsession
  chmod 755 $HOME/.xsession
fi

rm -f $TMP/tmpscript.sh $TMP/output

