#!/bin/sh

#mkdir ~/.vim/autoload
#curl -LSso ~/.vim/autoload/pathogen.vim https://tpo.pe/pathogen.vim

list="borland brief bufselect fileselect mru scratch"
for b in $list; do
	echo "$b"
	if [ -d $b/.git ]; then
		cd $b
		git pull
		cd ..
	else
		rm -rf $b
		git clone https://github.com/yegappan/$b
	fi
done

list=""
#list="$list https://github.com/preservim/nerdtree"
#list="$list https://github.com/vimwiki/vimwiki"
list="$list https://github.com/bling/vim-bufferline"
list="$list https://github.com/Shougo/unite.vim"
list="$list https://github.com/vim-airline/vim-airline"
#list="$list https://github.com/theniceboy/vim-calc"
list="$list https://github.com/frazrepo/vim-rainbow"
for b in $list; do
	p=$(basename $b)
	echo "$p"
	if [ -d $p/.git ]; then
		cd $p
		git pull
		cd ..
	else
		rm -rf $p
		git clone $b
	fi
done
