#!/bin/sh
#
#	Package and service manager for Void Linux
#
#	Copyright (C) 2019, Nicholas Christopoulos <nereus@freemail.gr>
#
#	This program is free software; you can redistribute it and/or modify it
#	under the terms of the GNU General Public License as published by the Free
#	Software Foundation; either version 3 of the License, or (at your option)
#	any later version.
#

msghelp="
Void-utils Main Application\n\
\n\
Packages (void-package):\n\
\t-u  | update/upgrade\tupdate package list and upgrade all installed packages\n\
\t-i  | install ...\tinstall package[s]\n\
\t-r  | remove ...\t\tremove package[s]\n\
\t-s  | search <pattern>\tsearch for packages by matching package-name\n\
\t-w  | show | info | view ...\tdisplay information about package[s]\n\
\t-f  | file-search ...\tsearch file in packages\n\
\n\
\t-o\t\t\tremove obsolete packages\n\
\t-rc | reconfigure ...\n\
\t-k\t\t\tremove old kernels\n\
\t--files <package>\tshows the files of the package\n\
\n\
Services (void-service):\n\
\t-e | enable ...\t\tenable service[s]\n\
\t-d | disable ...\tdisable service[s]\n\
\t-E | enabled\t\tdisplay all enabled services\n\
\t-D | disabled\t\tdisplay all disabled services\n\
\tstart | stop | restart | reload | status ...\n\
\t\t\t\tsv <action> <service>\n\
\n\
More (void-*):\n\
\t-m\t\t\tsystem maintenance\n\
"

msgvers="\
void-linux-utils version $(void-utils-version)\n\n\
Copyright (C) 2019 Nicholas Christopoulos <mailto:nereus@freemail.gr>.\n\
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.\n\
This is free software: you are free to change and redistribute it.\n\
There is NO WARRANTY, to the extent permitted by law."

###
todo=help
if [ $# -gt 0 ]; then todo="$1"; shift; fi

case $todo in
# void-package
-u|update|upgrade)	void-package -u;;
-i|install|-r|remove|reinstall|-w|info|show|view|-s|search|-rs|regex-search|-fs|file-search)
	void-package $todo $*
	;;
-o|-rc|-k|-rok|-f|--files|-a|-af|-ia|-ai)
	void-package $todo $*
	;;

# void-service
-e|enable)	void-service -e $*;;
-d|disable)	void-service -d $*;;
-E|enabled) void-service -E;;
-D|disabled) void-service -D;;
-L|list)	void-service -L;;
start|stop|status|restart|reload)
	void-service $todo $*
	;;

-m|maintenance)
	void-maintenance
	;;

-v|--version)	
	echo $msgvers
	exit 1
	;;

-h|--help|help|*)
	echo $msghelp
	exit 1
	;;

esac
