#!/bin/sh
#
#	Copyright (C) 2019, Nicholas Christopoulos <nereus@freemail.gr>
#
#	This program is free software; you can redistribute it and/or modify it
#	under the terms of the GNU General Public License as published by the Free
#	Software Foundation; either version 3 of the License, or (at your option)
#	any later version.
#

msghelp="\
Usage: void-gui-disable\n\n\
Disables GUI login kit, next time it will starts from console."

#
msgvers="\
void-linux-utils version 1.0\n\n\
Copyright (C) 2019 Nicholas Christopoulos <mailto:nereus@freemail.gr>.\n\
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.\n\
This is free software: you are free to change and redistribute it.\n\
There is NO WARRANTY, to the extent permitted by law."

#
red="\033[1;31m"
gre="\033[1;32m"
yel="\033[1;33m"
rst="\033[0m"

_help() { echo $msghelp; exit 1; }
_vers() { echo $msgvers; exit 1; }
#if [ $# -eq 0 ]; then _help; fi
if [ "$1" = "-h" -o "$1" = "--help" ]; then _help; fi
if [ "$1" = "-v" -o "$1" = "--version" ]; then _vers; fi

dmlst="cdm gdm lightdm nodm sddm xdm"
curdm="lightdm"
for x in $dmlst; do
	if pgrep -x "$x" 2>&1 > /dev/null; then
		curdm="$x"
		break
	fi
done

void-service -d dbus cgmanager polkitd $curdm


