#!/bin/sh
#
#	Copyright (C) 2019, Nicholas Christopoulos <nereus@freemail.gr>
#
#	This program is free software; you can redistribute it and/or modify it
#	under the terms of the GNU General Public License as published by the Free
#	Software Foundation; either version 3 of the License, or (at your option)
#	any later version.
#

msghelp="\
System maintenance for Void Linux\n\
"

msgvers="\
void-linux-utils version 1.0\n\n\
Copyright (C) 2019 Nicholas Christopoulos <mailto:nereus@freemail.gr>.\n\
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.\n\
This is free software: you are free to change and redistribute it.\n\
There is NO WARRANTY, to the extent permitted by law."

###
title="\033[1;32m"
rst="\033[0m"

for o in $*; do
	if [ $o = "-h" -o $o = "--help" ]; then echo $msghelp; exit 1; fi
	if [ $o = "-v" -o $o = "--version" ]; then echo $msgvers; exit 1; fi
done

###
cnt=0
echo "${title}VOID LINUX, SYSTEM MAINTENANCE"
echo 

cnt=$((cnt+1))
echo "${title}${cnt}. Upgrade packages${rst}"
xbps-install -Suy

cnt=$((cnt+1))
echo "${title}${cnt}. Update xlocate database${rst}"
xlocate -S

cnt=$((cnt+1))
echo "${title}${cnt}. Remove obsolete packages${rst}"
xbps-remove -Oo

cnt=$((cnt+1))
echo "${title}${cnt}. Remove old kernels${rst}"
vkpurge rm all

cnt=$((cnt+1))
echo "${title}${cnt}. Update locate's db${rst}"
updatedb

cnt=$((cnt+1))
echo "${title}${cnt}. Update MAN db${rst}"
makewhatis -a -Tutf8

cnt=$((cnt+1))
echo "${title}${cnt}. Trim SSD${rst}"
fstrim -v /

echo "${title}* done *${rst}"

