#!/bin/sh

msghelp="\
Usage: void-list-services [-e|-d] [-n]\n\n\
\t-e, --enabled\tPrints enabled services only\n\
\t-d, --disabled\tPrints disabled services only\n\
\t-p, --plain\tPrints service names only\n\
\n\
Prints all services and their status.
Use -e to get list of enabled or -d of disabled services only."

#
msgvers="\
void-libux-utils version 1.0\n\n\
Copyright (C) 2019 Nicholas Christopoulos <mailto:nereus@freemail.gr>.\n\
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.\n\
This is free software: you are free to change and redistribute it.\n\
There is NO WARRANTY, to the extent permitted by law."

#
red="\033[1;31m"
gre="\033[1;32m"
yel="\033[1;33m"
rst="\033[0m"

_help() { echo $msghelp; exit 1; }
_vers() { echo $msgvers; exit 1; }
#if [ $# -eq 0 ]; then _help; fi

enabled_only=0
disabled_only=0
plain=0
for o in $*; do
	if [ "$o" = "-h" -o "$o" = "--help" ]; then _help; fi
	if [ "$o" = "-v" -o "$o" = "--version" ]; then _vers; fi
	if [ "$o" = "-e" -o "$o" = "--enabled"  ]; then enabled_only=1; fi
	if [ "$o" = "-d" -o "$o" = "--disabled" ]; then disabled_only=1; fi
	if [ "$o" = "-p" -o "$o" = "--plain" ]; then plain=1; fi
done

#
for f in /etc/sv/*; do
	s=${f##*/}
	if [ -e /var/service/$s ]; then
		if [ $disabled_only -eq 0 ]; then
			if [ $plain -eq 1 ]; then
				echo "$s"
			else
				echo "+ ${gre}enabled  ${yel}$s${rst}"
			fi
		fi
	else
		if [ $enabled_only -eq 0 ]; then
			if [ $plain -eq 1 ]; then
				echo "$s"
			else
				echo "- ${red}disabled ${yel}$s${rst}"
			fi
		fi
	fi
done

