#!/bin/sh
#
#	Package and service manager for Void Linux
#
#	Copyright (C) 2019, Nicholas Christopoulos <nereus@freemail.gr>
#
#	This program is free software; you can redistribute it and/or modify it
#	under the terms of the GNU General Public License as published by the Free
#	Software Foundation; either version 3 of the License, or (at your option)
#	any later version.
#

msghelp="
Package and service manager for Void Linux\n\
\n\
Packages:\n\
\t-i  | install ...\tinstall package[s]\n\
\t-r  | remove ...\t\tremove package[s]\n\
\t-u  | update ...\t\tupdate package list and upgrade all installed packages\n\
\treinstall ...\t\treinstall package[s]\n\
\t-s  | search <pattern>\tsearch for packages by matching package-name\n\
\t-w  | show | info | view ...\tdisplay information about package[s]\n\
\t-f  | file-search ...\tsearch file in packages\n\
\t-a[f|i] pattern\t\tfind all pacakges [f] = and format for xargs, [i] = and install\n\
\n\
Services (void-service):\n\
\t-e | enable ...\t\tenable service[s]\n\
\t-d | disable ...\tdisable service[s]\n\
\t-E | enabled\t\tdisplay all enabled services\n\
\t-D | disabled\t\tdisplay all disabled services\n\
\tstart | stop | restart | reload | status ...\n\
\t\t\t\tsv <action> <service>\n\
\n\
Special:\n\
\t-o   | autoremove\t\tremove obsolete packages\n\
\t-rc  | reconfigure ...\n\
\t-k\t\t\tremove old kernels\n\
\t--files <package>\tshows the files of the package\n\
"

msgvers="\
void-linux-utils version 1.0\n\n\
Copyright (C) 2019 Nicholas Christopoulos <mailto:nereus@freemail.gr>.\n\
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.\n\
This is free software: you are free to change and redistribute it.\n\
There is NO WARRANTY, to the extent permitted by law."

###
todo=help
if [ $# -gt 0 ]; then todo="$1"; shift; fi

case $todo in
#
#	basic package utilities
#
-i|install)	xbps-install $*	;;
-r|remove)	xbps-remove $*	;;
reinstall)
	xbps-remove $*
	xbps-install -y $*
	;;
-u|update)
	xbps-install -Su $*
	echo "update xlocate database"
	xlocate -S
	;;

#
#	advanced package utilities
#
-w|info|show|view)	xbps-query -R -S $*	;;
-s|search)			xbps-query -Rs "$*"	;;
-rs|regex-search)	xbps-query --regex -Rs "$*";;
-f|-fs|file-search)
	xbps-query --regex -Ro "$*"
	xlocate "$*"
	;;

#
#	services
#
-e|enable)	void-service -e $*;;
-d|disable)	void-service -d $*;;
start|stop|status|restart|reload)
	for f in $*; do
		case $f in
		avahi)		service=avahi-daemon;;
		nfs|nfsd)	service=nfs-server;;
		samba|smb)	service=smbd;;
		*)			service=$f
		esac
		sv $todo $service
	done
	;;
	
-E|enabled)			void-service -E ;;
-D|disabled)		void-service -D ;;
-o|autoremove)		xbps-remove -Oo ;;
-rc|reconfigure)	xbps-reconfigure -f $* ;;
-k|-rok)
	vkpurge rm all ;;
--files)
	xbps-query -f $*
	;;

-a)
	xbps-query --regex -Rs "$argv[2-]" | grep -v 32bit
	;;
-af)
	xbps-query --regex -Rs "$argv[2-]" | grep -v 32bit | awk '{print $2}'
	;;
-ia|-ai)
	xbps-query --regex -Rs "$argv[2-]" | grep -v 32bit | awk '{print $2}' | xargs xbps-install -y
	;;

-v|--version)	
	echo $msgvers
	exit 1
	;;
-h|--help|help|*)
	echo $msghelp
	exit 1
	;;
esac
